spring:
  graphql:
    schema:
      locations: classpath*:graphql/
  application:
    name: FamilyAccountManager
  data:
    mongodb:
      uri: mongodb://localhost:27017/event-store
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.packages: "*"
        spring.json.trusted.packages: "ru.dorin.familyaccountmanager.integration.event"
    listener:
      ack-mode: record
      error-handler:
        recoverer:
          dead-letter:
            topic-suffix: .DLT



application:
  eventStore:
    type: ${EVENT_STORE_TYPE:inMemory}
  integration:
    publisher: ${PUBLISHER_TYPE:context}
  kafka:
    enabled: ${KAFKA_ENABLED:false}
    topic:
      integration-event: family-account-manager.integration-event
    outbox:
      relay-interval-ms: 10000
